# fly.toml app configuration file generated for fly-streamlit on 2024-06-29T17:53:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-streamlit'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
